### ISSUE TITLE
Where is your release?

### ISSUE THREAD

**Issue by E3V3A** [rogerorr/NtTrace#1]
When will you make a release?

**Comment by rogerorr** [comment]
Do you have a specific requirement/reason ?

**Comment by ContegoCode** [comment]
Is this release working yet for anyone?

**Comment by E3V3A** [comment]
> Do you have a specific requirement/reason ?

Strange question...  I'm obviously trying to find something better and more Windows oriented than the outdated `strace`  on Cygwin. (If your keeping the code here, and up-to-date, why don't you post the releases, so that we can test or even help you?

**Comment by rogerorr** [comment]
Ha - but "obviously" is rarely so to other people. There can be a range of reasons why people need/want a 'release version' of something: for example so they can refer to 'release X.Y' in their own code.
I've not bothered to do formal releases of NtTrace on GitHub - I originally wrote it just for my own debugging, and have added it to GitHub in case others found it useful.

**Comment by rogerorr** [comment]
I've just tagged the current master as "v1.0" so those who need one have a release version
