### ISSUE TITLE
Running NtTrace interferes with the process(es) being traced.

### ISSUE THREAD

**Issue by chrisj-unity** [rogerorr/NtTrace#3]
Hi,

If I run a command with NtTrace, the results of running the command ought to be the same as running the command without NtTrace. This doesn't always seem to be the case.

A simple example is using NtTrace to log the output of NtTrace's own build process. This example was done with Windows 10 version 1803, using Visual Studio 2017.

1. Open a **x64 Native Tools Command Prompt for VS 2017**
2. Clone the repository into a directory called src1: **git clone git@github.com:rogerorr/NtTrace.git src1**
3. Enter the new directory src1: **cd src1**
4. Build the tool with **nmake /f NtTrace.mak**
5. Observe the tool builds successfully.
6. Go back to the parent directory: **cd ..**
7. Clone the repository into another directory called src2 **git clone git@github.com:rogerorr/NtTrace.git src2**
8. Enter the new directory src2: **cd src2**
9. Use the tool built in step 4 to trace the build process in src2. i.e. **..\src1\NtTrace.exe -out logfile.txt nmake /f NtTrace.mak**
10. The build process fails to complete and no NtTrace.exe is created.

**Comment by rogerorr** [comment]
Thank you for the clear bug report.
I can reproduce the issue using the steps you described, and after the commit I can now successfully build (step 9)
