### ISSUE TITLE
Slight documentation error

### ISSUE THREAD

**Issue by JohnPSYMQEPDFQ** [rogerorr/NtTrace#4]
You might want to add that if you compile BOTH versions of the executable (eg 32 bit & 64 bit) back-to-back, the "build" directory must be removed before the second make is run.  Otherwise the second build will fail.

I spent hours on this, thinking it was a ".lib" path problem.  

So,  after doing this:

"C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvarsall.bat" x86
nmake /f NtTrace.mak

Do this:
rmdir /r build

Then, you can do this:
"C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvarsall.bat" x64
nmake /f NtTrace.mak

**Comment by rogerorr** [comment]
Sorry to hear the problem delayed you a long time.

I've changed the  Makefile in commit 9cc52ca to build into build32 and build64 directories, so you can build both versions at the same time; I hope this helps.

**Comment by JohnPSYMQEPDFQ** [comment]
Ahh,  a much better solution.

This is a fabulous utility, btw.    

Thanks.
